/**
 * httpbin
 * An unofficial OpenAPI definition for [httpbin.org](https://httpbin.org).
 *
 * The version of the OpenAPI document: 1.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.core._
import alias._
import sttp.client._
import sttp.model.Method

object CookiesApi {

  def apply(baseUrl: String = "https://httpbin.org")(implicit serializer: SttpSerializer) = new CookiesApi(baseUrl)
}

class CookiesApi(baseUrl: String)(implicit serializer: SttpSerializer) {

  import Helpers._
  import serializer._

  /**
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param freeform Enter free-form query parameters in the JSON format `{ \"param1\": \"value1\", \"param2\": \"value2\", ... }`.  Note that the parameters will be actually sent as `?param1=value1&param2=value2&...` 
   */
  def cookiesDeleteGet(freeform: Map[String, Any]): ApiRequestT[Unit] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/cookies/delete?freeform=$freeform")
      .contentType("application/json")
      .response(asJson[Unit])

  /**
   * Expected answers:
   *   code 200 :  (OK)
   */
  def cookiesGet(): ApiRequestT[Unit] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/cookies")
      .contentType("application/json")
      .response(asJson[Unit])

  /**
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param freeform Enter free-form query parameters in the JSON format `{ \"param1\": \"value1\", \"param2\": \"value2\", ... }`.  Note that the parameters will be actually sent as `?param1=value1&param2=value2&...` 
   */
  def cookiesSetGet(freeform: Map[String, Any]): ApiRequestT[Unit] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/cookies/set?freeform=$freeform")
      .contentType("application/json")
      .response(asJson[Unit])

}

