/**
 * httpbin
 * An unofficial OpenAPI definition for [httpbin.org](https://httpbin.org).
 *
 * The version of the OpenAPI document: 1.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import org.openapitools.client.model.CommonResponse
import org.openapitools.client.core._
import alias._
import sttp.client._
import sttp.model.Method

object HTTPMethodsApi {

  def apply(baseUrl: String = "https://httpbin.org")(implicit serializer: SttpSerializer) = new HTTPMethodsApi(baseUrl)
}

class HTTPMethodsApi(baseUrl: String)(implicit serializer: SttpSerializer) {

  import Helpers._
  import serializer._

  /**
   * Expected answers:
   *   code 200 :  (OK)
   * 
   * @param freeform Enter free-form query parameters in the JSON format `{ \"param1\": \"value1\", \"param2\": \"value2\", ... }`.  Note that the parameters will be actually sent as `?param1=value1&param2=value2&...` 
   */
  def deleteDelete(freeform: Map[String, Any]): ApiRequestT[Unit] =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/delete?freeform=$freeform")
      .contentType("application/json")
      .response(asJson[Unit])

  /**
   * Expected answers:
   *   code 200 : Any (OK)
   * 
   * @param freeform Enter free-form query parameters in the JSON format `{ \"param1\": \"value1\", \"param2\": \"value2\", ... }`.  Note that the parameters will be actually sent as `?param1=value1&param2=value2&...` 
   */
  def getGet(freeform: Map[String, Any]): ApiRequestT[Any] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/get?freeform=$freeform")
      .contentType("application/json")
      .response(asJson[Any])

  /**
   * Expected answers:
   *   code 200 : CommonResponse (OK)
   * 
   * @param freeform Enter free-form query parameters in the JSON format `{ \"param1\": \"value1\", \"param2\": \"value2\", ... }`.  Note that the parameters will be actually sent as `?param1=value1&param2=value2&...` 
   * @param body Data provided in the request body will be returned in the response.
   */
  def postPost(freeform: Map[String, Any], body: Option[AnyType] = None): ApiRequestT[CommonResponse] =
    basicRequest
      .method(Method.POST, uri"$baseUrl/post?freeform=$freeform")
      .contentType("application/json")
      .body(body)
      .response(asJson[CommonResponse])

}

