/**
 * httpbin
 * An unofficial OpenAPI definition for [httpbin.org](https://httpbin.org).
 *
 * The version of the OpenAPI document: 1.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.api

import java.io.File
import org.openapitools.client.core._
import alias._
import sttp.client._
import sttp.model.Method

object ImagesApi {

  def apply(baseUrl: String = "https://httpbin.org")(implicit serializer: SttpSerializer) = new ImagesApi(baseUrl)
}

class ImagesApi(baseUrl: String)(implicit serializer: SttpSerializer) {

  import Helpers._
  import serializer._

  /**
   * Expected answers:
   *   code 200 : File (OK)
   * 
   * @param format 
   */
  def imageFormatGet(format: String): ApiRequestT[File] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/image/${format}")
      .contentType("application/json")
      .response(asJson[File])

  /**
   * Expected answers:
   *   code 200 : File (OK)
   *   code 406 :  (Client did not request a supported media type.)
   */
  def imageGet(): ApiRequestT[File] =
    basicRequest
      .method(Method.GET, uri"$baseUrl/image")
      .contentType("application/json")
      .response(asJson[File])

}

