/**
 * httpbin
 * An unofficial OpenAPI definition for [httpbin.org](https://httpbin.org).
 *
 * The version of the OpenAPI document: 1.0-oas3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel

case class PostResponseAllOf(
  data: Option[AnyType] = None,
  files: Option[AnyType] = None,
  /* Form parameters specified in \"application/x-www-form-urlencoded\" and `multipart/form-data` requests.  */
  form: Option[Map[String, String]] = None,
  /* JSON value sent in the payload. Can be object, array, string, number, boolean or `null`.  */
  json: Option[AnyType] = None
) extends ApiModel


